baseURL = "http://mns.k.u-tokyo.ac.jp/~hirakawa/"
publishDir = "docs"
title = "Tomoya Hirakawa"
theme = "erblog"
googleAnalytics = "G-EFPVBSGRVG"
paginate = 3
languageCode = "jp"
DefaultContentLanguage = "jp"
hasCJKLanguage = true
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[params]
    author = "Tomoya HIRAKAWA"
    badge = "orange"
    quote = "red"
    notice = "Recent: 僕の財布も緊急事態宣言。"
    description = "インドに行きたい。"
    notice_color = "red"
    index_posts_num = 5
    google_search = true
    math = true
    # logo = "icon.jpg"
    # logo = "self/img/avater.jpg"
    bio = """
    <h2> Tomoya HIRAKAWA  (1997. 12.16) </h2>
    <p>2013.4 - 2018.3 久留米高専制御情報工学科</p>
    <p>2018.4 - 2020.3 久留米高専専攻科（学士）</p>
    <p>2020.4 - Current 東京大学大学院新領域創成科学研究科</p>
    <br />
    <h2>Interest</h2>
    <ul>
    <b>現在の研究テーマ</b>
    <li>ベイズ統計・機械学習</li>
    <li>データ駆動科学</li>
    <b>かじってたテーマ</b>
    <li>信号処理・画像認識</li>
    </ul>
    <br />
    </br>
    <h2>Publications</h2>
    [Conference] T. Hirakawa, K. Chigita and Y. Kuroki, "Distributed compressed hyper spectral image sensing using ADMM," 2018 International Workshop on Advanced Image Technology (IWAIT), 2018, pp. 1-4, doi: 10.1109/IWAIT.2018.8369758.
    <br />
    <br />
    [Conference] T. Hirakawa, K. Wararatpanya, and Y. Kuroki. "Image recognition using multi-layer sparse feature extraction with ADMM." International Workshop on Advanced Image Technology (IWAIT) 2019. Vol. 11049. International Society for Optics and Photonics, 2019.
    <br />
    <br />
    [Conference] T. Hirakawa and Y. Kuroki, "Image classification on projection based multilayer sparse representation," 2019 IEEE 8th Global Conference on Consumer Electronics (GCCE), 2019, pp. 1069-1070, doi: 10.1109/GCCE46687.2019.9014638.
    <br />
    <br />
    [Conference] T. Hirakawa, S. Kubota and Y. Kuroki, "Image Classification by Multilayer Feature Extraction Based on Nuclear Norm Minimization," 2019 International Symposium on Intelligent Signal Processing and Communication Systems (ISPACS), 2019, pp. 1-2, doi: 10.1109/ISPACS48206.2019.8986349.
    <br />
    <br />
    <h2>Hobby</h2>
    <ul>
    <li>映画：洋画，邦画問わずの雑食</li>
    <li>読書：沢木耕太郎さんの『深夜特急』が特に好き</li>
    <li>カメラ：元写真部@高専</li>
    </ul>
    """
    og_image = "self/img/thumnail.png"
    #copyright = "Copyright © 2020, Steve Francia and the Hugo Authors; all rights reserved. This page was created by Hugo."
    copyright = "Copyright © 2020, Tomoya HIRAKAWA"

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[[menu.main]]
    identifier = "gallery"
    name = "Gallery"
    url = "/gallery/"
    weight = 20

# [[menu.main]]
#     identifier = "zone"
#     name = "Zone"
#     url = "/zone/"
#     weight = 10

[[menu.footer]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[menu.footer]]
    identifier = "gallery"
    name = "Gallery"
    url = "/gallery/"
    weight = 2

[[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[menu.icon]]
    url = "mailto:hirakawa@mns.k.u-tokyo.ac.jp"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/t0m0ya1997/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/t_dopeness"
    name = "twitter"
    weight = 1

[[menu.icon]]
    url = "https://www.instagram.com/tomoya19971216/"
    name = "instagram"
    weight = 1
