baseURL = "https://t0m0ya1997.github.io/blog"
publishDir = "docs"
title = "Tomoya Hirakawa"
theme = "erblog"
paginate = 3
languageCode = "jp"
DefaultContentLanguage = "jp"
hasCJKLanguage = true
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[params]
    author = "Tomoya HIRAKAWA"
    badge = "orange"
    quote = "red"
    notice = "就職活動始めたぽよ。"
    description = "インドに行きたいブログ。"
    notice_color = "red"
    index_posts_num = 5
    google_search = true
    math = true
    # logo = "icon.jpg"
    # logo = "//blog.ertuil.top/avater.png"
    bio = """
    <h2> Tomoya HIRAKAWA  (1997. 12.16) </h2>
    <p>2013.4 - 2018.3 久留米高専制御情報工学科</p>
    <p>2018.4 - 2020.3 久留米高専専攻科（学士）</p>
    <p>2020.4 - current 東京大学大学院新領域創成科学研究科</p>
    <br />
    <h2>Interest</h2>
    <ul>
    <li>ベイズ統計・機械学習：現在の研究テーマに関わっています.</li>
    <li>データ駆動科学：現在の研究テーマに関わっています.</li>
    <li>信号処理・画像認識：高専時代に研究をしていました.</li>
    </ul>
    <br />
    <h2>Hobby</h2>
    <ul>
    <li>映画：洋画，邦画問わずの雑食です．『フォレスト・ガンプ』を最近観ました．</li>
    <li>読書：沢木耕太郎さんの『深夜特急』が好きです．</li>
    <li>カメラ：元写真部員（高専）です.</li>
    </ul>
    """
    #copyright = "Copyright © 2020, Steve Francia and the Hugo Authors; all rights reserved. This page was created by Hugo."
    copyright = "Copyright © 2020, Tomoya HIRAKAWA, the Hugo Authors, and Steve Francia"

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

# [[menu.main]]
#     identifier = "zone"
#     name = "Zone"
#     url = "/zone/"
#     weight = 10

[[menu.footer]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1

[[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[menu.icon]]
    url = "mailto:hirakawa@mns.k.u-tokyo.ac.jp"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/t0m0ya1997/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/t_dopeness"
    name = "twitter"
    weight = 1

[[menu.icon]]
    url = "https://www.instagram.com/tomoya19971216/"
    name = "instagram"
    weight = 1
